-- AlterTable
ALTER TABLE "respostas_missao" ADD COLUMN     "data_inicio" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "resposta" DROP NOT NULL,
ALTER COLUMN "status" SET DEFAULT 'INICIADA',
ALTER COLUMN "data_envio" DROP NOT NULL,
ALTER COLUMN "data_envio" DROP DEFAULT;
